module.exports = {
    DECREMENT_MAIN_COUNTER: 'DECREMENT_MAIN_COUNTER',
    INCREMENT_MAIN_COUNTER: 'INCREMENT_MAIN_COUNTER',

    SET_USER_NAME: 'SET_USER_NAME',
    SET_USER_AGE: 'SET_USER_AGE',
};